insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Silverado 2500', 2005, 72);
insert into cars (maker, model, year, person_id) values ('Saab', '9-5', 2004, 852);
insert into cars (maker, model, year, person_id) values ('Saturn', 'VUE', 2009, 887);
insert into cars (maker, model, year, person_id) values ('BMW', 'Z8', 2003, 882);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'GLK-Class', 2011, 724);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Echo', 2000, 560);
insert into cars (maker, model, year, person_id) values ('Volkswagen', 'Passat', 2002, 612);
insert into cars (maker, model, year, person_id) values ('Buick', 'LeSabre', 1991, 868);
insert into cars (maker, model, year, person_id) values ('Infiniti', 'G35', 2003, 952);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'Lancer', 2004, 92);
insert into cars (maker, model, year, person_id) values ('Saturn', 'VUE', 2007, 529);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'Montero', 1997, 616);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Sportvan G10', 1992, 303);
insert into cars (maker, model, year, person_id) values ('Ford', 'Escape', 2009, 525);
insert into cars (maker, model, year, person_id) values ('Jeep', 'Liberty', 2009, 710);
insert into cars (maker, model, year, person_id) values ('MINI', 'Cooper', 2008, 517);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Corvette', 2004, 272);
insert into cars (maker, model, year, person_id) values ('Chevrolet', '2500', 1996, 73);
insert into cars (maker, model, year, person_id) values ('Cadillac', 'CTS', 2004, 194);
insert into cars (maker, model, year, person_id) values ('Nissan', 'Frontier', 2004, 120);
insert into cars (maker, model, year, person_id) values ('Mercury', 'Marauder', 2004, 832);
insert into cars (maker, model, year, person_id) values ('Ford', 'Mustang', 1970, 267);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'S-Class', 1985, 840);
insert into cars (maker, model, year, person_id) values ('Volkswagen', 'Corrado', 1994, 132);
insert into cars (maker, model, year, person_id) values ('GMC', 'Sierra 2500', 2004, 445);
insert into cars (maker, model, year, person_id) values ('BMW', 'M Roadster', 2008, 721);
insert into cars (maker, model, year, person_id) values ('Buick', 'Riviera', 1995, 166);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Ram', 2010, 137);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Land Cruiser', 1997, 478);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Cavalier', 2004, 446);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'GTO', 1968, 24);
insert into cars (maker, model, year, person_id) values ('Honda', 'Insight', 2010, 734);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Avalanche', 2010, 922);
insert into cars (maker, model, year, person_id) values ('Cadillac', 'Fleetwood', 1992, 870);
insert into cars (maker, model, year, person_id) values ('Nissan', 'Quest', 1997, 311);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'LeMans', 1964, 26);
insert into cars (maker, model, year, person_id) values ('Lexus', 'ES', 2008, 902);
insert into cars (maker, model, year, person_id) values ('Porsche', 'Boxster', 2003, 377);
insert into cars (maker, model, year, person_id) values ('Volkswagen', 'Cabriolet', 1987, 289);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Echo', 2005, 504);
insert into cars (maker, model, year, person_id) values ('Audi', 'A4', 2000, 723);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Suburban 1500', 2000, 223);
insert into cars (maker, model, year, person_id) values ('Pontiac', '6000', 1989, 443);
insert into cars (maker, model, year, person_id) values ('Volkswagen', 'GTI', 2010, 518);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'Expo LRV', 1996, 785);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Malibu', 1997, 119);
insert into cars (maker, model, year, person_id) values ('Buick', 'LeSabre', 1993, 113);
insert into cars (maker, model, year, person_id) values ('Scion', 'tC', 2010, 302);
insert into cars (maker, model, year, person_id) values ('Suzuki', 'Vitara', 2003, 405);
insert into cars (maker, model, year, person_id) values ('Cadillac', 'DTS', 2010, 333);
insert into cars (maker, model, year, person_id) values ('Maybach', '62', 2004, 417);
insert into cars (maker, model, year, person_id) values ('Jaguar', 'XK Series', 2013, 453);
insert into cars (maker, model, year, person_id) values ('Bentley', 'Arnage', 2007, 764);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Land Cruiser', 1995, 37);
insert into cars (maker, model, year, person_id) values ('Lincoln', 'Continental', 1991, 210);
insert into cars (maker, model, year, person_id) values ('Kia', 'Amanti', 2008, 275);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Tracker', 1999, 294);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Silverado', 2009, 99);
insert into cars (maker, model, year, person_id) values ('Chrysler', 'Sebring', 2010, 114);
insert into cars (maker, model, year, person_id) values ('Volkswagen', 'Touareg', 2005, 148);
insert into cars (maker, model, year, person_id) values ('Honda', 'Accord', 1995, 954);
insert into cars (maker, model, year, person_id) values ('Ford', 'Aspire', 1995, 366);
insert into cars (maker, model, year, person_id) values ('Porsche', 'Boxster', 2001, 306);
insert into cars (maker, model, year, person_id) values ('GMC', 'Envoy XL', 2003, 723);
insert into cars (maker, model, year, person_id) values ('Acura', 'NSX', 2000, 166);
insert into cars (maker, model, year, person_id) values ('Lincoln', 'Blackwood', 2002, 313);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Suburban', 2007, 345);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'Firebird', 2001, 316);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Dakota Club', 2002, 874);
insert into cars (maker, model, year, person_id) values ('Mazda', 'MPV', 1990, 330);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Sportvan G30', 1993, 31);
insert into cars (maker, model, year, person_id) values ('Mazda', 'B-Series', 1987, 144);
insert into cars (maker, model, year, person_id) values ('Ram', '2500', 2012, 254);
insert into cars (maker, model, year, person_id) values ('Kia', 'Carens', 2008, 987);
insert into cars (maker, model, year, person_id) values ('Ferrari', '612 Scaglietti', 2007, 934);
insert into cars (maker, model, year, person_id) values ('GMC', '3500 Club Coupe', 1997, 835);
insert into cars (maker, model, year, person_id) values ('Hummer', 'H1', 2004, 698);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'S-Class', 2008, 386);
insert into cars (maker, model, year, person_id) values ('Porsche', '968', 1994, 441);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Sienna', 2009, 850);
insert into cars (maker, model, year, person_id) values ('Saab', '9-3', 2012, 848);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Lumina', 1997, 968);
insert into cars (maker, model, year, person_id) values ('Isuzu', 'Oasis', 1997, 183);
insert into cars (maker, model, year, person_id) values ('Maybach', '62', 2010, 506);
insert into cars (maker, model, year, person_id) values ('Lexus', 'ES', 2000, 947);
insert into cars (maker, model, year, person_id) values ('Lotus', 'Esprit', 1993, 133);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'SLK-Class', 2009, 171);
insert into cars (maker, model, year, person_id) values ('Cadillac', 'Catera', 1998, 360);
insert into cars (maker, model, year, person_id) values ('Land Rover', 'Discovery', 2005, 520);
insert into cars (maker, model, year, person_id) values ('Oldsmobile', 'LSS', 1998, 515);
insert into cars (maker, model, year, person_id) values ('GMC', 'Suburban 2500', 1998, 188);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Camry Hybrid', 2008, 462);
insert into cars (maker, model, year, person_id) values ('Mazda', 'Protege', 1992, 777);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Camaro', 1999, 182);
insert into cars (maker, model, year, person_id) values ('Honda', 'Element', 2009, 278);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Aveo', 2010, 907);
insert into cars (maker, model, year, person_id) values ('Buick', 'Skyhawk', 1987, 584);
insert into cars (maker, model, year, person_id) values ('Suzuki', 'Swift', 1999, 352);
insert into cars (maker, model, year, person_id) values ('Ferrari', '430 Scuderia', 2009, 93);
insert into cars (maker, model, year, person_id) values ('Acura', 'Integra', 1988, 742);
insert into cars (maker, model, year, person_id) values ('Ford', 'Crown Victoria', 2003, 255);
insert into cars (maker, model, year, person_id) values ('Saturn', 'Astra', 2008, 333);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'G-Series 1500', 1998, 665);
insert into cars (maker, model, year, person_id) values ('Honda', 'Prelude', 1986, 594);
insert into cars (maker, model, year, person_id) values ('Mercury', 'Cougar', 1988, 436);
insert into cars (maker, model, year, person_id) values ('Ford', 'ZX2', 2002, 52);
insert into cars (maker, model, year, person_id) values ('Cadillac', 'Escalade', 2002, 359);
insert into cars (maker, model, year, person_id) values ('Infiniti', 'G', 2002, 57);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Ram 1500', 2003, 492);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Suburban', 2009, 895);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Solara', 2001, 721);
insert into cars (maker, model, year, person_id) values ('Alfa Romeo', '164', 1994, 933);
insert into cars (maker, model, year, person_id) values ('Buick', 'LeSabre', 1992, 112);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Caprice Classic', 1996, 756);
insert into cars (maker, model, year, person_id) values ('BMW', '760', 2004, 201);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Express 2500', 1999, 874);
insert into cars (maker, model, year, person_id) values ('GMC', 'Jimmy', 1995, 340);
insert into cars (maker, model, year, person_id) values ('Mazda', 'MPV', 2003, 271);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Ram Van B350', 1994, 358);
insert into cars (maker, model, year, person_id) values ('Chrysler', 'LeBaron', 1995, 868);
insert into cars (maker, model, year, person_id) values ('Aston Martin', 'DB9', 2006, 906);
insert into cars (maker, model, year, person_id) values ('GMC', 'Canyon', 2009, 673);
insert into cars (maker, model, year, person_id) values ('Peugeot', '207', 2006, 575);
insert into cars (maker, model, year, person_id) values ('Jaguar', 'XK Series', 2000, 107);
insert into cars (maker, model, year, person_id) values ('Ford', 'Econoline E350', 2001, 708);
insert into cars (maker, model, year, person_id) values ('Lincoln', 'MKS', 2009, 778);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Land Cruiser', 2013, 754);
insert into cars (maker, model, year, person_id) values ('Infiniti', 'FX', 2010, 752);
insert into cars (maker, model, year, person_id) values ('Ford', 'E-Series', 1985, 560);
insert into cars (maker, model, year, person_id) values ('Land Rover', 'Range Rover', 2001, 907);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'CL-Class', 1998, 404);
insert into cars (maker, model, year, person_id) values ('Volkswagen', 'GTI', 2006, 568);
insert into cars (maker, model, year, person_id) values ('Volvo', 'S70', 1998, 706);
insert into cars (maker, model, year, person_id) values ('GMC', 'Vandura 3500', 1993, 521);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Viper', 1995, 179);
insert into cars (maker, model, year, person_id) values ('BMW', 'M3', 2003, 389);
insert into cars (maker, model, year, person_id) values ('Porsche', '911', 2001, 955);
insert into cars (maker, model, year, person_id) values ('Lamborghini', 'Diablo', 1995, 601);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Camry Hybrid', 2007, 149);
insert into cars (maker, model, year, person_id) values ('Toyota', 'T100', 1995, 206);
insert into cars (maker, model, year, person_id) values ('Subaru', 'Impreza', 2001, 991);
insert into cars (maker, model, year, person_id) values ('Lexus', 'RX', 2009, 724);
insert into cars (maker, model, year, person_id) values ('Honda', 'Passport', 1994, 278);
insert into cars (maker, model, year, person_id) values ('Lamborghini', 'Aventador', 2012, 44);
insert into cars (maker, model, year, person_id) values ('Dodge', 'D150', 1992, 555);
insert into cars (maker, model, year, person_id) values ('Ford', 'E150', 2005, 20);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Corolla', 2000, 158);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'GTO', 1965, 783);
insert into cars (maker, model, year, person_id) values ('GMC', 'Yukon Denali', 2000, 23);
insert into cars (maker, model, year, person_id) values ('Volkswagen', 'Touareg 2', 2009, 11);
insert into cars (maker, model, year, person_id) values ('Ford', 'Bronco', 1989, 814);
insert into cars (maker, model, year, person_id) values ('Audi', 'A6', 2000, 24);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Camaro', 1967, 390);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Citation', 1980, 917);
insert into cars (maker, model, year, person_id) values ('Ford', 'E350', 2007, 928);
insert into cars (maker, model, year, person_id) values ('BMW', '600', 1959, 230);
insert into cars (maker, model, year, person_id) values ('Ford', 'Focus', 2003, 258);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'C-Class', 1998, 806);
insert into cars (maker, model, year, person_id) values ('Acura', 'NSX', 1992, 723);
insert into cars (maker, model, year, person_id) values ('Toyota', 'RAV4', 2004, 906);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Corvette', 1972, 52);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'E-Class', 2003, 783);
insert into cars (maker, model, year, person_id) values ('Jeep', 'Commander', 2008, 144);
insert into cars (maker, model, year, person_id) values ('BMW', 'Z4', 2006, 81);
insert into cars (maker, model, year, person_id) values ('Cadillac', 'XLR', 2005, 908);
insert into cars (maker, model, year, person_id) values ('Mercury', 'Grand Marquis', 2000, 646);
insert into cars (maker, model, year, person_id) values ('Mercury', 'Mountaineer', 2010, 764);
insert into cars (maker, model, year, person_id) values ('Honda', 'Crosstour', 2012, 906);
insert into cars (maker, model, year, person_id) values ('BMW', 'M3', 2005, 78);
insert into cars (maker, model, year, person_id) values ('Nissan', 'Maxima', 2000, 571);
insert into cars (maker, model, year, person_id) values ('Audi', 'A8', 2004, 341);
insert into cars (maker, model, year, person_id) values ('Aptera', '2e', 2009, 694);
insert into cars (maker, model, year, person_id) values ('Cadillac', 'Fleetwood', 1995, 80);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Sequoia', 2002, 942);
insert into cars (maker, model, year, person_id) values ('Mazda', 'Protege', 1998, 329);
insert into cars (maker, model, year, person_id) values ('Cadillac', 'XLR-V', 2008, 113);
insert into cars (maker, model, year, person_id) values ('Hyundai', 'Elantra', 1995, 714);
insert into cars (maker, model, year, person_id) values ('Audi', '80/90', 1988, 972);
insert into cars (maker, model, year, person_id) values ('Suzuki', 'Daewoo Lacetti', 2008, 755);
insert into cars (maker, model, year, person_id) values ('Nissan', 'Frontier', 1998, 659);
insert into cars (maker, model, year, person_id) values ('Saab', '9-3', 2010, 655);
insert into cars (maker, model, year, person_id) values ('Volkswagen', 'Tiguan', 2011, 186);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Express 2500', 2001, 753);
insert into cars (maker, model, year, person_id) values ('Kia', 'Optima', 2003, 785);
insert into cars (maker, model, year, person_id) values ('Bentley', 'Continental GTC', 2011, 650);
insert into cars (maker, model, year, person_id) values ('Nissan', 'Titan', 2005, 445);
insert into cars (maker, model, year, person_id) values ('Mercury', 'Mystique', 1997, 900);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Silverado 1500', 2011, 829);
insert into cars (maker, model, year, person_id) values ('Plymouth', 'Neon', 1997, 467);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'Grand Am', 1998, 507);
insert into cars (maker, model, year, person_id) values ('Subaru', 'Tribeca', 2008, 237);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Grand Caravan', 2003, 570);
insert into cars (maker, model, year, person_id) values ('Cadillac', 'Eldorado', 2001, 357);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'S-Class', 1991, 276);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Camaro', 1971, 746);
insert into cars (maker, model, year, person_id) values ('Audi', 'V8', 1994, 253);
insert into cars (maker, model, year, person_id) values ('Ford', 'Expedition', 2004, 87);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'Endeavor', 2009, 240);
insert into cars (maker, model, year, person_id) values ('BMW', 'M6', 2007, 709);
insert into cars (maker, model, year, person_id) values ('Mercury', 'Cougar', 1967, 892);
insert into cars (maker, model, year, person_id) values ('BMW', '6 Series', 2008, 135);
insert into cars (maker, model, year, person_id) values ('Acura', 'Vigor', 1992, 941);
insert into cars (maker, model, year, person_id) values ('Lamborghini', 'Murciélago', 2006, 564);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'S-Class', 1991, 662);
insert into cars (maker, model, year, person_id) values ('Ford', 'Thunderbird', 1994, 540);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'Mirage', 1985, 364);
insert into cars (maker, model, year, person_id) values ('Suzuki', 'XL-7', 2007, 395);
insert into cars (maker, model, year, person_id) values ('Nissan', 'Xterra', 2001, 630);
insert into cars (maker, model, year, person_id) values ('Land Rover', 'Defender', 1993, 972);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Monte Carlo', 2001, 738);
insert into cars (maker, model, year, person_id) values ('Lincoln', 'Navigator', 2012, 130);
insert into cars (maker, model, year, person_id) values ('Austin', 'Mini Cooper', 1961, 219);
insert into cars (maker, model, year, person_id) values ('BMW', '5 Series', 1993, 351);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'LeMans', 1966, 378);
insert into cars (maker, model, year, person_id) values ('GMC', 'Sierra 1500', 2009, 113);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Viper', 2009, 871);
insert into cars (maker, model, year, person_id) values ('GMC', 'Yukon', 2013, 111);
insert into cars (maker, model, year, person_id) values ('Maserati', 'Coupe', 2006, 524);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'S-Class', 1994, 871);
insert into cars (maker, model, year, person_id) values ('BMW', '330', 2005, 599);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Matrix', 2008, 582);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Express 2500', 2004, 912);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Neon', 1999, 984);
insert into cars (maker, model, year, person_id) values ('Audi', 'S4', 2008, 653);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Sienna', 2007, 777);
insert into cars (maker, model, year, person_id) values ('Honda', 'Civic', 1988, 272);
insert into cars (maker, model, year, person_id) values ('Ford', 'Taurus', 2010, 504);
insert into cars (maker, model, year, person_id) values ('Mazda', 'MPV', 2001, 820);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Suburban 2500', 2009, 194);
insert into cars (maker, model, year, person_id) values ('Volvo', 'C70', 2006, 982);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Equinox', 2007, 299);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'Galant', 2001, 557);
insert into cars (maker, model, year, person_id) values ('Saturn', 'Aura', 2008, 473);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', '300E', 1992, 131);
insert into cars (maker, model, year, person_id) values ('Ford', 'Escape', 2008, 745);
insert into cars (maker, model, year, person_id) values ('BMW', 'X3', 2005, 86);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Camry', 2010, 453);
insert into cars (maker, model, year, person_id) values ('Hyundai', 'Elantra', 2002, 731);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'Bonneville', 2001, 469);
insert into cars (maker, model, year, person_id) values ('BMW', 'X3', 2012, 347);
insert into cars (maker, model, year, person_id) values ('Ford', 'F250', 2008, 142);
insert into cars (maker, model, year, person_id) values ('Honda', 'S2000', 2004, 575);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'C-Class', 2001, 336);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'Bonneville', 1985, 152);
insert into cars (maker, model, year, person_id) values ('Toyota', '4Runner', 2001, 795);
insert into cars (maker, model, year, person_id) values ('Plymouth', 'Neon', 1995, 821);
insert into cars (maker, model, year, person_id) values ('Volvo', 'S40', 2005, 952);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Bel Air', 1967, 245);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Avalanche 2500', 2002, 839);
insert into cars (maker, model, year, person_id) values ('GMC', 'Yukon XL 1500', 2006, 999);
insert into cars (maker, model, year, person_id) values ('Jaguar', 'XK', 2010, 776);
insert into cars (maker, model, year, person_id) values ('Hyundai', 'Sonata', 2007, 591);
insert into cars (maker, model, year, person_id) values ('Audi', '80', 1990, 379);
insert into cars (maker, model, year, person_id) values ('Chrysler', 'Imperial', 1992, 419);
insert into cars (maker, model, year, person_id) values ('GMC', 'Savana 1500', 2007, 801);
insert into cars (maker, model, year, person_id) values ('Corbin', 'Sparrow', 2004, 999);
insert into cars (maker, model, year, person_id) values ('Ford', 'F-Series', 2003, 459);
insert into cars (maker, model, year, person_id) values ('Lexus', 'ES', 1998, 88);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Avalanche 2500', 2006, 707);
insert into cars (maker, model, year, person_id) values ('Infiniti', 'QX', 2009, 721);
insert into cars (maker, model, year, person_id) values ('Lexus', 'ES', 2001, 757);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'Bonneville', 1985, 386);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Caliber', 2011, 40);
insert into cars (maker, model, year, person_id) values ('BMW', 'M3', 2009, 788);
insert into cars (maker, model, year, person_id) values ('GMC', 'Sierra 1500', 2013, 560);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'i-MiEV', 2012, 288);
insert into cars (maker, model, year, person_id) values ('Lincoln', 'Navigator L', 2012, 222);
insert into cars (maker, model, year, person_id) values ('MINI', 'Cooper', 2006, 518);
insert into cars (maker, model, year, person_id) values ('MINI', 'Cooper', 2012, 217);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', '600SEC', 1993, 649);
insert into cars (maker, model, year, person_id) values ('Ford', 'Windstar', 1997, 312);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Ram 1500 Club', 1997, 365);
insert into cars (maker, model, year, person_id) values ('Subaru', 'Legacy', 2007, 591);
insert into cars (maker, model, year, person_id) values ('Bentley', 'Continental Flying Spur', 2009, 447);
insert into cars (maker, model, year, person_id) values ('Nissan', 'Murano', 2010, 860);
insert into cars (maker, model, year, person_id) values ('GMC', 'Envoy', 2007, 592);
insert into cars (maker, model, year, person_id) values ('Infiniti', 'J', 1997, 866);
insert into cars (maker, model, year, person_id) values ('Nissan', 'Versa', 2007, 474);
insert into cars (maker, model, year, person_id) values ('Volkswagen', 'Passat', 2008, 769);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Camry', 2001, 743);
insert into cars (maker, model, year, person_id) values ('Toyota', 'MR2', 1985, 5);
insert into cars (maker, model, year, person_id) values ('Aptera', 'Typ-1', 2008, 904);
insert into cars (maker, model, year, person_id) values ('Land Rover', 'Range Rover', 1993, 710);
insert into cars (maker, model, year, person_id) values ('Volvo', 'S40', 2011, 413);
insert into cars (maker, model, year, person_id) values ('Subaru', 'B9 Tribeca', 2006, 775);
insert into cars (maker, model, year, person_id) values ('Porsche', 'Cayman', 2012, 819);
insert into cars (maker, model, year, person_id) values ('Mazda', 'Mazda5', 2007, 513);
insert into cars (maker, model, year, person_id) values ('Mercury', 'Topaz', 1984, 564);
insert into cars (maker, model, year, person_id) values ('Jaguar', 'X-Type', 2004, 245);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'Challenger', 1997, 819);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Colorado', 2011, 375);
insert into cars (maker, model, year, person_id) values ('BMW', '3 Series', 1995, 136);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Caliber', 2011, 455);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Celica', 2002, 483);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'CLS-Class', 2009, 442);
insert into cars (maker, model, year, person_id) values ('Hummer', 'H2', 2004, 210);
insert into cars (maker, model, year, person_id) values ('Ford', 'Tempo', 1991, 198);
insert into cars (maker, model, year, person_id) values ('Lexus', 'SC', 1995, 117);
insert into cars (maker, model, year, person_id) values ('Mercury', 'Cougar', 1970, 941);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Cruze', 2011, 115);
insert into cars (maker, model, year, person_id) values ('Lotus', 'Esprit', 1988, 736);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'Grand Am', 1998, 810);
insert into cars (maker, model, year, person_id) values ('Subaru', 'Forester', 1999, 193);
insert into cars (maker, model, year, person_id) values ('Honda', 'Civic', 2002, 949);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Express 3500', 2008, 807);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Stealth', 1993, 617);
insert into cars (maker, model, year, person_id) values ('Suzuki', 'Swift', 2004, 915);
insert into cars (maker, model, year, person_id) values ('Plymouth', 'Acclaim', 1992, 838);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'Outlander', 2011, 744);
insert into cars (maker, model, year, person_id) values ('Subaru', 'Outback', 2007, 95);
insert into cars (maker, model, year, person_id) values ('Lotus', 'Elan', 1994, 732);
insert into cars (maker, model, year, person_id) values ('Mazda', 'Millenia', 1998, 9);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'S-Class', 2008, 853);
insert into cars (maker, model, year, person_id) values ('Mazda', 'B-Series', 1999, 1000);
insert into cars (maker, model, year, person_id) values ('Audi', 'TT', 2000, 104);
insert into cars (maker, model, year, person_id) values ('Saturn', 'S-Series', 2000, 391);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Solara', 1999, 937);
insert into cars (maker, model, year, person_id) values ('Land Rover', 'Defender 90', 1997, 693);
insert into cars (maker, model, year, person_id) values ('Volvo', 'S80', 1999, 337);
insert into cars (maker, model, year, person_id) values ('GMC', 'Safari', 1999, 304);
insert into cars (maker, model, year, person_id) values ('Honda', 'Civic', 2010, 469);
insert into cars (maker, model, year, person_id) values ('Mercury', 'Sable', 1986, 914);
insert into cars (maker, model, year, person_id) values ('Maserati', 'Quattroporte', 1986, 703);
insert into cars (maker, model, year, person_id) values ('Lexus', 'GS', 2008, 854);
insert into cars (maker, model, year, person_id) values ('Hyundai', 'Equus', 2012, 294);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Highlander', 2009, 339);
insert into cars (maker, model, year, person_id) values ('Jaguar', 'X-Type', 2008, 305);
insert into cars (maker, model, year, person_id) values ('Nissan', 'Sentra', 2001, 979);
insert into cars (maker, model, year, person_id) values ('Mazda', 'Mazda2', 2011, 320);
insert into cars (maker, model, year, person_id) values ('Mazda', 'Millenia', 2000, 265);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Colorado', 2009, 201);
insert into cars (maker, model, year, person_id) values ('Subaru', 'Justy', 1988, 621);
insert into cars (maker, model, year, person_id) values ('GMC', 'Suburban 2500', 1996, 608);
insert into cars (maker, model, year, person_id) values ('Mercury', 'Cougar', 2001, 145);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Durango', 2006, 800);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Impala', 2006, 884);
insert into cars (maker, model, year, person_id) values ('Lotus', 'Elan', 1994, 259);
insert into cars (maker, model, year, person_id) values ('Shelby', 'GT350', 1969, 579);
insert into cars (maker, model, year, person_id) values ('Infiniti', 'M', 2004, 627);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'SL-Class', 1989, 348);
insert into cars (maker, model, year, person_id) values ('Ford', 'Fiesta', 2013, 841);
insert into cars (maker, model, year, person_id) values ('Suzuki', 'Sidekick', 1992, 413);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Cavalier', 1996, 541);
insert into cars (maker, model, year, person_id) values ('Chrysler', '300M', 2002, 718);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Cobalt', 2005, 633);
insert into cars (maker, model, year, person_id) values ('Ford', 'Explorer', 1994, 232);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Grand Caravan', 2008, 544);
insert into cars (maker, model, year, person_id) values ('Kia', 'Rio', 2004, 571);
insert into cars (maker, model, year, person_id) values ('Land Rover', 'Discovery', 1995, 477);
insert into cars (maker, model, year, person_id) values ('BMW', 'Z4', 2012, 702);
insert into cars (maker, model, year, person_id) values ('Ford', 'F-Series', 1989, 735);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Venture', 2000, 210);
insert into cars (maker, model, year, person_id) values ('Jaguar', 'XJ', 2012, 981);
insert into cars (maker, model, year, person_id) values ('GMC', 'Sonoma', 1993, 690);
insert into cars (maker, model, year, person_id) values ('Maybach', '57', 2005, 362);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'RVR', 1995, 542);
insert into cars (maker, model, year, person_id) values ('Suzuki', 'Grand Vitara', 2004, 560);
insert into cars (maker, model, year, person_id) values ('MINI', 'Clubman', 2010, 962);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'HHR', 2007, 87);
insert into cars (maker, model, year, person_id) values ('GMC', 'Sierra 2500', 1999, 545);
insert into cars (maker, model, year, person_id) values ('Nissan', 'Altima', 2008, 435);
insert into cars (maker, model, year, person_id) values ('Mercury', 'Topaz', 1985, 313);
insert into cars (maker, model, year, person_id) values ('Ford', 'Explorer', 1991, 923);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Highlander', 2010, 492);
insert into cars (maker, model, year, person_id) values ('Scion', 'xB', 2006, 29);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Tacoma', 2012, 344);
insert into cars (maker, model, year, person_id) values ('BMW', 'M3', 2010, 156);
insert into cars (maker, model, year, person_id) values ('Mazda', 'B-Series Plus', 1992, 343);
insert into cars (maker, model, year, person_id) values ('Cadillac', 'SRX', 2006, 721);
insert into cars (maker, model, year, person_id) values ('Land Rover', 'Discovery Series II', 1999, 966);
insert into cars (maker, model, year, person_id) values ('Volvo', 'S70', 1998, 321);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Matrix', 2007, 26);
insert into cars (maker, model, year, person_id) values ('Mazda', 'MPV', 1995, 922);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'S-Class', 1988, 757);
insert into cars (maker, model, year, person_id) values ('Lincoln', 'Town Car', 2002, 282);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'GLK-Class', 2011, 675);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'Grand Prix', 1981, 908);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Silverado', 2010, 835);
insert into cars (maker, model, year, person_id) values ('Audi', 'A3', 2011, 452);
insert into cars (maker, model, year, person_id) values ('Jeep', 'Wrangler', 1994, 436);
insert into cars (maker, model, year, person_id) values ('Lotus', 'Esprit', 1987, 894);
insert into cars (maker, model, year, person_id) values ('Mazda', 'B-Series', 1994, 863);
insert into cars (maker, model, year, person_id) values ('Volkswagen', 'GTI', 1999, 153);
insert into cars (maker, model, year, person_id) values ('Ford', 'Mustang', 1970, 174);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Tacoma Xtra', 2000, 907);
insert into cars (maker, model, year, person_id) values ('GMC', 'Savana', 2011, 640);
insert into cars (maker, model, year, person_id) values ('Lexus', 'ES', 1998, 33);
insert into cars (maker, model, year, person_id) values ('Ford', 'Mustang', 2000, 579);
insert into cars (maker, model, year, person_id) values ('Kia', 'Spectra', 2000, 55);
insert into cars (maker, model, year, person_id) values ('GMC', 'Yukon XL 1500', 2013, 97);
insert into cars (maker, model, year, person_id) values ('Mazda', '626', 1989, 994);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Silverado', 2008, 474);
insert into cars (maker, model, year, person_id) values ('Eagle', 'Talon', 1997, 16);
insert into cars (maker, model, year, person_id) values ('Jeep', 'Cherokee', 1993, 105);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'G-Class', 2006, 966);
insert into cars (maker, model, year, person_id) values ('Isuzu', 'Trooper', 1999, 829);
insert into cars (maker, model, year, person_id) values ('Plymouth', 'Voyager', 1993, 569);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Silverado 2500', 1999, 455);
insert into cars (maker, model, year, person_id) values ('Land Rover', 'Range Rover Sport', 2008, 367);
insert into cars (maker, model, year, person_id) values ('Infiniti', 'QX56', 2010, 570);
insert into cars (maker, model, year, person_id) values ('GMC', 'Yukon XL 2500', 2003, 531);
insert into cars (maker, model, year, person_id) values ('Aston Martin', 'DB9 Volante', 2006, 501);
insert into cars (maker, model, year, person_id) values ('BMW', 'X6', 2012, 186);
insert into cars (maker, model, year, person_id) values ('Audi', '5000S', 1986, 158);
insert into cars (maker, model, year, person_id) values ('Porsche', '911', 1985, 65);
insert into cars (maker, model, year, person_id) values ('Oldsmobile', '98', 1996, 185);
insert into cars (maker, model, year, person_id) values ('Nissan', 'Quest', 2000, 355);
insert into cars (maker, model, year, person_id) values ('Toyota', 'RAV4', 2011, 435);
insert into cars (maker, model, year, person_id) values ('Oldsmobile', 'Ciera', 1995, 477);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Corvette', 1992, 182);
insert into cars (maker, model, year, person_id) values ('Aston Martin', 'DB9', 2005, 1);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Matrix', 2003, 120);
insert into cars (maker, model, year, person_id) values ('Mercury', 'Mariner', 2007, 392);
insert into cars (maker, model, year, person_id) values ('Mazda', 'RX-8', 2011, 988);
insert into cars (maker, model, year, person_id) values ('Mercury', 'Topaz', 1986, 412);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Bel Air', 1967, 493);
insert into cars (maker, model, year, person_id) values ('Maserati', 'Quattroporte', 1985, 945);
insert into cars (maker, model, year, person_id) values ('Kia', 'Sedona', 2003, 460);
insert into cars (maker, model, year, person_id) values ('Mazda', 'B-Series Plus', 1998, 458);
insert into cars (maker, model, year, person_id) values ('Hyundai', 'Accent', 1995, 537);
insert into cars (maker, model, year, person_id) values ('Ford', 'Flex', 2009, 888);
insert into cars (maker, model, year, person_id) values ('Audi', 'TT', 2004, 475);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'Montana', 2006, 304);
insert into cars (maker, model, year, person_id) values ('Chevrolet', '2500', 1995, 966);
insert into cars (maker, model, year, person_id) values ('Ford', 'Econoline E250', 2001, 145);
insert into cars (maker, model, year, person_id) values ('Kia', 'Sportage', 2006, 223);
insert into cars (maker, model, year, person_id) values ('Porsche', '928', 1993, 366);
insert into cars (maker, model, year, person_id) values ('Mazda', 'Mazda6', 2009, 521);
insert into cars (maker, model, year, person_id) values ('Plymouth', 'Laser', 1992, 997);
insert into cars (maker, model, year, person_id) values ('Buick', 'Century', 1996, 931);
insert into cars (maker, model, year, person_id) values ('Lexus', 'IS', 2004, 406);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'Lancer Evolution', 2008, 27);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'CL-Class', 2002, 919);
insert into cars (maker, model, year, person_id) values ('Ford', 'Econoline E350', 1994, 62);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'Truck', 1989, 169);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Ram 1500', 2002, 910);
insert into cars (maker, model, year, person_id) values ('Bentley', 'Continental Flying Spur', 2012, 539);
insert into cars (maker, model, year, person_id) values ('Ford', 'F350', 2008, 632);
insert into cars (maker, model, year, person_id) values ('Volvo', 'XC60', 2010, 305);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'Pajero', 1993, 467);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Suburban 1500', 1997, 728);
insert into cars (maker, model, year, person_id) values ('GMC', 'Envoy XL', 2005, 804);
insert into cars (maker, model, year, person_id) values ('Ford', 'Ranger', 1989, 453);
insert into cars (maker, model, year, person_id) values ('GMC', 'Sierra 1500', 2012, 172);
insert into cars (maker, model, year, person_id) values ('Suzuki', 'Grand Vitara', 2002, 803);
insert into cars (maker, model, year, person_id) values ('Lexus', 'GS', 2005, 242);
insert into cars (maker, model, year, person_id) values ('Ford', 'Mustang', 2010, 149);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Dakota', 2011, 101);
insert into cars (maker, model, year, person_id) values ('Audi', 'S8', 2009, 748);
insert into cars (maker, model, year, person_id) values ('GMC', 'Savana', 2011, 745);
insert into cars (maker, model, year, person_id) values ('Kia', 'Sorento', 2003, 844);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Camry Hybrid', 2009, 605);
insert into cars (maker, model, year, person_id) values ('GMC', 'Sierra 1500', 2008, 647);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Corvette', 1969, 413);
insert into cars (maker, model, year, person_id) values ('Hummer', 'H2', 2004, 318);
insert into cars (maker, model, year, person_id) values ('Kia', 'Sephia', 1999, 642);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'R-Class', 2007, 59);
insert into cars (maker, model, year, person_id) values ('Mercury', 'Marquis', 1984, 133);
insert into cars (maker, model, year, person_id) values ('Jaguar', 'XK', 2011, 118);
insert into cars (maker, model, year, person_id) values ('GMC', 'Sierra 1500', 2011, 952);
insert into cars (maker, model, year, person_id) values ('Ford', 'F450', 2010, 398);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Suburban 2500', 2001, 952);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Express 2500', 2007, 131);
insert into cars (maker, model, year, person_id) values ('Porsche', 'Boxster', 2003, 721);
insert into cars (maker, model, year, person_id) values ('Mercury', 'Villager', 1996, 721);
insert into cars (maker, model, year, person_id) values ('Acura', 'MDX', 2002, 295);
insert into cars (maker, model, year, person_id) values ('Plymouth', 'Laser', 1991, 978);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Avalanche', 2011, 222);
insert into cars (maker, model, year, person_id) values ('GMC', 'Yukon XL 2500', 2013, 588);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Camaro', 1999, 631);
insert into cars (maker, model, year, person_id) values ('Nissan', '200SX', 1995, 213);
insert into cars (maker, model, year, person_id) values ('Suzuki', 'SX4', 2011, 868);
insert into cars (maker, model, year, person_id) values ('Subaru', 'Legacy', 2010, 147);
insert into cars (maker, model, year, person_id) values ('Volvo', 'XC90', 2012, 989);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Intrepid', 2003, 720);
insert into cars (maker, model, year, person_id) values ('Nissan', 'Altima', 2008, 650);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'Fiero', 1984, 217);
insert into cars (maker, model, year, person_id) values ('Ford', 'Thunderbird', 1997, 947);
insert into cars (maker, model, year, person_id) values ('BMW', '6 Series', 2008, 1);
insert into cars (maker, model, year, person_id) values ('Mazda', 'CX-7', 2008, 631);
insert into cars (maker, model, year, person_id) values ('Lincoln', 'MKX', 2007, 399);
insert into cars (maker, model, year, person_id) values ('Aston Martin', 'DBS', 2012, 554);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'Montero', 2002, 43);
insert into cars (maker, model, year, person_id) values ('Hyundai', 'Veloster', 2012, 792);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Caravan', 2002, 851);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Impala', 2011, 984);
insert into cars (maker, model, year, person_id) values ('Kia', 'Optima', 2001, 220);
insert into cars (maker, model, year, person_id) values ('Lexus', 'LS', 1989, 410);
insert into cars (maker, model, year, person_id) values ('Land Rover', 'LR4', 2010, 767);
insert into cars (maker, model, year, person_id) values ('GMC', 'Rally Wagon 3500', 1993, 25);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'Gemini', 1987, 839);
insert into cars (maker, model, year, person_id) values ('Volkswagen', 'Type 2', 1985, 9);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'Cordia', 1984, 861);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Camaro', 1994, 44);
insert into cars (maker, model, year, person_id) values ('Ford', 'Focus', 2012, 916);
insert into cars (maker, model, year, person_id) values ('Cadillac', 'Catera', 1997, 682);
insert into cars (maker, model, year, person_id) values ('Austin', 'Mini Cooper', 1961, 120);
insert into cars (maker, model, year, person_id) values ('Ford', 'Thunderbird', 2003, 619);
insert into cars (maker, model, year, person_id) values ('Infiniti', 'I', 1996, 828);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Viper', 2010, 608);
insert into cars (maker, model, year, person_id) values ('Lincoln', 'Town Car', 1991, 333);
insert into cars (maker, model, year, person_id) values ('Subaru', 'Loyale', 1993, 912);
insert into cars (maker, model, year, person_id) values ('Chevrolet', '3500', 1995, 793);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Solara', 2003, 288);
insert into cars (maker, model, year, person_id) values ('Cadillac', 'Escalade ESV', 2011, 753);
insert into cars (maker, model, year, person_id) values ('Plymouth', 'Reliant', 1981, 747);
insert into cars (maker, model, year, person_id) values ('Ford', 'F-Series', 2010, 273);
insert into cars (maker, model, year, person_id) values ('Infiniti', 'G', 2012, 122);
insert into cars (maker, model, year, person_id) values ('Infiniti', 'QX', 2007, 939);
insert into cars (maker, model, year, person_id) values ('GMC', 'Yukon XL 1500', 2001, 483);
insert into cars (maker, model, year, person_id) values ('Ford', 'Escape', 2009, 996);
insert into cars (maker, model, year, person_id) values ('Chrysler', 'Crossfire', 2007, 989);
insert into cars (maker, model, year, person_id) values ('Saab', '900', 1988, 16);
insert into cars (maker, model, year, person_id) values ('Lexus', 'RX Hybrid', 2010, 961);
insert into cars (maker, model, year, person_id) values ('Ford', 'Expedition', 2002, 897);
insert into cars (maker, model, year, person_id) values ('Cadillac', 'Escalade EXT', 2007, 988);
insert into cars (maker, model, year, person_id) values ('Volvo', '940', 1994, 203);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Camaro', 2010, 987);
insert into cars (maker, model, year, person_id) values ('GMC', 'Envoy', 2003, 513);
insert into cars (maker, model, year, person_id) values ('Ford', 'Mustang', 2011, 786);
insert into cars (maker, model, year, person_id) values ('Honda', 'Civic Si', 2006, 435);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Celica', 1996, 539);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Corvette', 1975, 886);
insert into cars (maker, model, year, person_id) values ('Lincoln', 'Town Car', 1988, 450);
insert into cars (maker, model, year, person_id) values ('BMW', 'X5', 2001, 748);
insert into cars (maker, model, year, person_id) values ('Ford', 'Escort ZX2', 2003, 1000);
insert into cars (maker, model, year, person_id) values ('Subaru', 'Justy', 1994, 713);
insert into cars (maker, model, year, person_id) values ('Saab', '9-7X', 2007, 275);
insert into cars (maker, model, year, person_id) values ('Suzuki', 'Grand Vitara', 2001, 980);
insert into cars (maker, model, year, person_id) values ('GMC', 'Yukon', 1994, 321);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'GTO', 1970, 188);
insert into cars (maker, model, year, person_id) values ('Lexus', 'LX', 2005, 97);
insert into cars (maker, model, year, person_id) values ('Hyundai', 'Azera', 2011, 284);
insert into cars (maker, model, year, person_id) values ('Lexus', 'RX', 2009, 604);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Avalanche 2500', 2004, 244);
insert into cars (maker, model, year, person_id) values ('Isuzu', 'Rodeo Sport', 2002, 637);
insert into cars (maker, model, year, person_id) values ('Ford', 'Explorer Sport Trac', 2004, 8);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Venza', 2012, 99);
insert into cars (maker, model, year, person_id) values ('Honda', 'Odyssey', 2010, 623);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Dakota', 2011, 298);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'GL-Class', 2009, 25);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Sportvan G10', 1992, 181);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'Mirage', 1987, 82);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'Montero', 1995, 118);
insert into cars (maker, model, year, person_id) values ('Isuzu', 'Space', 1994, 373);
insert into cars (maker, model, year, person_id) values ('Cadillac', 'CTS-V', 2009, 883);
insert into cars (maker, model, year, person_id) values ('Chrysler', '300M', 2000, 647);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Corolla', 2002, 243);
insert into cars (maker, model, year, person_id) values ('Land Rover', 'Range Rover Sport', 2012, 337);
insert into cars (maker, model, year, person_id) values ('Porsche', 'Cayenne', 2003, 553);
insert into cars (maker, model, year, person_id) values ('Nissan', 'Quest', 1999, 854);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Caprice', 1977, 139);
insert into cars (maker, model, year, person_id) values ('Lotus', 'Esprit', 1992, 771);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'Pajero', 1989, 784);
insert into cars (maker, model, year, person_id) values ('Chrysler', 'Sebring', 2005, 818);
insert into cars (maker, model, year, person_id) values ('Lincoln', 'Navigator', 2009, 914);
insert into cars (maker, model, year, person_id) values ('Subaru', 'Forester', 2000, 861);
insert into cars (maker, model, year, person_id) values ('Hyundai', 'Veracruz', 2012, 768);
insert into cars (maker, model, year, person_id) values ('Ford', 'Focus', 2003, 330);
insert into cars (maker, model, year, person_id) values ('Mazda', 'B-Series', 1995, 52);
insert into cars (maker, model, year, person_id) values ('Jeep', 'Wrangler', 1998, 675);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Impala', 1995, 284);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'G-Class', 2005, 679);
insert into cars (maker, model, year, person_id) values ('Kia', 'Sportage', 2007, 891);
insert into cars (maker, model, year, person_id) values ('Lexus', 'ES', 1995, 511);
insert into cars (maker, model, year, person_id) values ('Porsche', '911', 1995, 297);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Stealth', 1995, 170);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Suburban 2500', 1998, 349);
insert into cars (maker, model, year, person_id) values ('Porsche', '911', 1996, 109);
insert into cars (maker, model, year, person_id) values ('Audi', 'A3', 2012, 833);
insert into cars (maker, model, year, person_id) values ('Ford', 'Ranger', 2000, 451);
insert into cars (maker, model, year, person_id) values ('Mazda', '626', 1995, 747);
insert into cars (maker, model, year, person_id) values ('Buick', 'Skylark', 1987, 787);
insert into cars (maker, model, year, person_id) values ('Kia', 'Sportage', 2010, 738);
insert into cars (maker, model, year, person_id) values ('BMW', '3 Series', 1999, 448);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Suburban 2500', 2011, 248);
insert into cars (maker, model, year, person_id) values ('Hillman', 'Minx Magnificent', 1950, 800);
insert into cars (maker, model, year, person_id) values ('Lincoln', 'Navigator', 2009, 694);
insert into cars (maker, model, year, person_id) values ('Lexus', 'SC', 1998, 836);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'E-Class', 2010, 801);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Express 2500', 2006, 364);
insert into cars (maker, model, year, person_id) values ('Subaru', 'Justy', 1994, 727);
insert into cars (maker, model, year, person_id) values ('Chrysler', 'Town & Country', 1995, 556);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Sportvan G30', 1995, 810);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Prius', 2010, 782);
insert into cars (maker, model, year, person_id) values ('Jaguar', 'XJ Series', 2004, 166);
insert into cars (maker, model, year, person_id) values ('Ford', 'Escape', 2008, 330);
insert into cars (maker, model, year, person_id) values ('Jeep', 'Compass', 2011, 279);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'Grand Am', 2003, 376);
insert into cars (maker, model, year, person_id) values ('Audi', 'Q5', 2009, 807);
insert into cars (maker, model, year, person_id) values ('Saturn', 'Sky', 2009, 531);
insert into cars (maker, model, year, person_id) values ('Porsche', '928', 1990, 341);
insert into cars (maker, model, year, person_id) values ('Hyundai', 'Tiburon', 2005, 933);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'Grand Prix', 2000, 626);
insert into cars (maker, model, year, person_id) values ('Lexus', 'LX', 2006, 507);
insert into cars (maker, model, year, person_id) values ('GMC', 'Suburban 2500', 1996, 134);
insert into cars (maker, model, year, person_id) values ('Lamborghini', 'Diablo', 1992, 113);
insert into cars (maker, model, year, person_id) values ('Honda', 'Accord', 1992, 88);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Tahoe', 2009, 305);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Express 3500', 1996, 430);
insert into cars (maker, model, year, person_id) values ('Toyota', '4Runner', 2008, 363);
insert into cars (maker, model, year, person_id) values ('Aston Martin', 'Rapide', 2012, 162);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'S-Class', 1993, 863);
insert into cars (maker, model, year, person_id) values ('Ford', 'F250', 1995, 913);
insert into cars (maker, model, year, person_id) values ('Maserati', 'Karif', 1989, 486);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Paseo', 1997, 134);
insert into cars (maker, model, year, person_id) values ('Lincoln', 'Continental', 1998, 515);
insert into cars (maker, model, year, person_id) values ('Toyota', 'MR2', 1986, 548);
insert into cars (maker, model, year, person_id) values ('Acura', 'RL', 2003, 50);
insert into cars (maker, model, year, person_id) values ('Ford', 'Mustang', 2009, 973);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Tundra', 2010, 511);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'Truck', 1995, 80);
insert into cars (maker, model, year, person_id) values ('GMC', 'Rally Wagon G3500', 1996, 280);
insert into cars (maker, model, year, person_id) values ('Honda', 'Civic', 2004, 857);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'Montero Sport', 2001, 739);
insert into cars (maker, model, year, person_id) values ('Ford', 'Explorer', 2002, 357);
insert into cars (maker, model, year, person_id) values ('BMW', 'X3', 2006, 565);
insert into cars (maker, model, year, person_id) values ('BMW', '5 Series', 1998, 568);
insert into cars (maker, model, year, person_id) values ('Subaru', 'Baja', 2004, 555);
insert into cars (maker, model, year, person_id) values ('Isuzu', 'Amigo', 1992, 715);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Avalanche 1500', 2003, 910);
insert into cars (maker, model, year, person_id) values ('Ford', 'Fairlane', 1965, 658);
insert into cars (maker, model, year, person_id) values ('Ford', 'Explorer', 2006, 232);
insert into cars (maker, model, year, person_id) values ('Honda', 'Prelude', 1985, 251);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'E-Class', 2006, 545);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'SL-Class', 2005, 879);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'Trans Sport', 1995, 695);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Camry', 1998, 509);
insert into cars (maker, model, year, person_id) values ('Volkswagen', 'Cabriolet', 1997, 842);
insert into cars (maker, model, year, person_id) values ('Lamborghini', 'Diablo', 2000, 303);
insert into cars (maker, model, year, person_id) values ('GMC', 'Savana 2500', 2003, 242);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'E-Class', 1984, 694);
insert into cars (maker, model, year, person_id) values ('MINI', 'Cooper', 2008, 48);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Prius v', 2012, 860);
insert into cars (maker, model, year, person_id) values ('Land Rover', 'LR3', 2007, 961);
insert into cars (maker, model, year, person_id) values ('Acura', 'RL', 2001, 435);
insert into cars (maker, model, year, person_id) values ('Jaguar', 'S-Type', 2001, 956);
insert into cars (maker, model, year, person_id) values ('Suzuki', 'Swift', 1991, 927);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'Mighty Max Macro', 1992, 926);
insert into cars (maker, model, year, person_id) values ('Volvo', 'S40', 2004, 671);
insert into cars (maker, model, year, person_id) values ('Subaru', 'Forester', 2005, 497);
insert into cars (maker, model, year, person_id) values ('Porsche', 'Boxster', 2009, 757);
insert into cars (maker, model, year, person_id) values ('Volvo', 'XC70', 2008, 635);
insert into cars (maker, model, year, person_id) values ('Audi', 'Q7', 2008, 850);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'G-Series G30', 1995, 631);
insert into cars (maker, model, year, person_id) values ('Saturn', 'Ion', 2006, 915);
insert into cars (maker, model, year, person_id) values ('Lamborghini', 'Murciélago', 2009, 878);
insert into cars (maker, model, year, person_id) values ('Ford', 'Taurus', 1996, 57);
insert into cars (maker, model, year, person_id) values ('Suzuki', 'Samurai', 1995, 230);
insert into cars (maker, model, year, person_id) values ('Buick', 'Estate', 1990, 337);
insert into cars (maker, model, year, person_id) values ('Ford', 'F250', 1984, 87);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Ram 3500', 1998, 448);
insert into cars (maker, model, year, person_id) values ('Maybach', '62', 2011, 253);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'HHR', 2010, 427);
insert into cars (maker, model, year, person_id) values ('Buick', 'Lucerne', 2010, 145);
insert into cars (maker, model, year, person_id) values ('Kia', 'Sorento', 2009, 424);
insert into cars (maker, model, year, person_id) values ('Chrysler', 'Town & Country', 2003, 957);
insert into cars (maker, model, year, person_id) values ('Honda', 'Passport', 2002, 636);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'Lancer Evolution', 2004, 794);
insert into cars (maker, model, year, person_id) values ('Volvo', 'C70', 2010, 140);
insert into cars (maker, model, year, person_id) values ('Honda', 'Prelude', 1986, 701);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'S-Class', 1999, 680);
insert into cars (maker, model, year, person_id) values ('Lincoln', 'MKX', 2008, 687);
insert into cars (maker, model, year, person_id) values ('GMC', 'Envoy', 1998, 185);
insert into cars (maker, model, year, person_id) values ('Ford', 'Escort', 1986, 18);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Celica', 1997, 99);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Suburban 2500', 2007, 461);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Suburban', 2011, 420);
insert into cars (maker, model, year, person_id) values ('Lotus', 'Esprit', 2000, 735);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Express 3500', 2004, 767);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Ram Van 1500', 2002, 701);
insert into cars (maker, model, year, person_id) values ('Ford', 'Thunderbird', 1993, 48);
insert into cars (maker, model, year, person_id) values ('Audi', 'Quattro', 1994, 545);
insert into cars (maker, model, year, person_id) values ('Nissan', 'Sentra', 2007, 828);
insert into cars (maker, model, year, person_id) values ('Porsche', '924 S', 1987, 410);
insert into cars (maker, model, year, person_id) values ('Ford', 'E-Series', 2012, 362);
insert into cars (maker, model, year, person_id) values ('Acura', 'NSX', 2004, 54);
insert into cars (maker, model, year, person_id) values ('Volkswagen', 'Passat', 2005, 549);
insert into cars (maker, model, year, person_id) values ('Mazda', 'Tribute', 2001, 607);
insert into cars (maker, model, year, person_id) values ('Mazda', 'MPV', 1996, 102);
insert into cars (maker, model, year, person_id) values ('BMW', '6 Series', 2005, 380);
insert into cars (maker, model, year, person_id) values ('Subaru', 'Legacy', 1990, 406);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Silverado', 2006, 259);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Tacoma', 2007, 70);
insert into cars (maker, model, year, person_id) values ('Nissan', 'Frontier', 2003, 894);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Avalanche', 2012, 734);
insert into cars (maker, model, year, person_id) values ('Volkswagen', 'GTI', 2007, 109);
insert into cars (maker, model, year, person_id) values ('Honda', 'Pilot', 2003, 602);
insert into cars (maker, model, year, person_id) values ('Land Rover', 'Discovery', 2011, 86);
insert into cars (maker, model, year, person_id) values ('Land Rover', 'Freelander', 2004, 402);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Suburban 1500', 2003, 309);
insert into cars (maker, model, year, person_id) values ('Saab', '900', 1994, 69);
insert into cars (maker, model, year, person_id) values ('Honda', 'S2000', 2007, 560);
insert into cars (maker, model, year, person_id) values ('Toyota', '4Runner', 2010, 493);
insert into cars (maker, model, year, person_id) values ('MINI', 'Cooper Clubman', 2008, 939);
insert into cars (maker, model, year, person_id) values ('Mercury', 'Lynx', 1985, 916);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Avalanche', 2007, 603);
insert into cars (maker, model, year, person_id) values ('Austin', 'Mini Cooper', 1961, 891);
insert into cars (maker, model, year, person_id) values ('Ford', 'F350', 2001, 484);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Ram 3500', 1997, 365);
insert into cars (maker, model, year, person_id) values ('Cadillac', 'SRX', 2009, 389);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Tercel', 1998, 25);
insert into cars (maker, model, year, person_id) values ('Oldsmobile', 'Cutlass', 1997, 691);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Ram 3500', 2008, 318);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'SLK-Class', 2012, 535);
insert into cars (maker, model, year, person_id) values ('Lexus', 'IS', 2011, 619);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Ram Van 2500', 2003, 872);
insert into cars (maker, model, year, person_id) values ('Lexus', 'HS', 2011, 582);
insert into cars (maker, model, year, person_id) values ('Audi', 'S4', 1992, 859);
insert into cars (maker, model, year, person_id) values ('Lexus', 'GS', 1998, 201);
insert into cars (maker, model, year, person_id) values ('Ford', 'Thunderbird', 1987, 880);
insert into cars (maker, model, year, person_id) values ('Infiniti', 'QX56', 2012, 844);
insert into cars (maker, model, year, person_id) values ('Pontiac', '1000', 1986, 437);
insert into cars (maker, model, year, person_id) values ('Acura', 'NSX', 2004, 938);
insert into cars (maker, model, year, person_id) values ('Chevrolet', '2500', 1995, 218);
insert into cars (maker, model, year, person_id) values ('Lamborghini', 'Diablo', 1993, 54);
insert into cars (maker, model, year, person_id) values ('Suzuki', 'Aerio', 2006, 1000);
insert into cars (maker, model, year, person_id) values ('Scion', 'xD', 2012, 417);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Ram 1500', 2001, 872);
insert into cars (maker, model, year, person_id) values ('Jeep', 'Wrangler', 2012, 845);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Cobalt', 2006, 107);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'SLR McLaren', 2006, 771);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Ipsum', 2000, 523);
insert into cars (maker, model, year, person_id) values ('Honda', 'Insight', 2010, 922);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Tercel', 1995, 818);
insert into cars (maker, model, year, person_id) values ('Plymouth', 'Laser', 1992, 802);
insert into cars (maker, model, year, person_id) values ('Mazda', 'Mazdaspeed 3', 2007, 821);
insert into cars (maker, model, year, person_id) values ('Buick', 'Century', 2003, 912);
insert into cars (maker, model, year, person_id) values ('Oldsmobile', '98', 1992, 684);
insert into cars (maker, model, year, person_id) values ('Ford', 'F150', 1994, 519);
insert into cars (maker, model, year, person_id) values ('Ford', 'Contour', 1999, 865);
insert into cars (maker, model, year, person_id) values ('Nissan', 'NV3500', 2012, 447);
insert into cars (maker, model, year, person_id) values ('Buick', 'Regal', 2000, 58);
insert into cars (maker, model, year, person_id) values ('Maserati', 'Biturbo', 1986, 406);
insert into cars (maker, model, year, person_id) values ('Acura', 'NSX', 2000, 989);
insert into cars (maker, model, year, person_id) values ('BMW', '5 Series', 1993, 628);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Stealth', 1993, 708);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Malibu', 2005, 272);
insert into cars (maker, model, year, person_id) values ('Lincoln', 'Town Car', 2010, 28);
insert into cars (maker, model, year, person_id) values ('Subaru', 'Loyale', 1994, 253);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'W126', 1983, 838);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'Grand Prix', 1980, 950);
insert into cars (maker, model, year, person_id) values ('Nissan', 'Xterra', 2007, 625);
insert into cars (maker, model, year, person_id) values ('Jaguar', 'X-Type', 2006, 460);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Ram 2500', 1998, 319);
insert into cars (maker, model, year, person_id) values ('Lexus', 'LX', 2007, 301);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Ram Van 2500', 1998, 979);
insert into cars (maker, model, year, person_id) values ('Jaguar', 'S-Type', 2001, 390);
insert into cars (maker, model, year, person_id) values ('Chrysler', 'Cirrus', 1996, 346);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'Bonneville', 1965, 844);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Tacoma', 2002, 670);
insert into cars (maker, model, year, person_id) values ('Chrysler', 'Pacifica', 2004, 706);
insert into cars (maker, model, year, person_id) values ('Lexus', 'GS', 1997, 792);
insert into cars (maker, model, year, person_id) values ('GMC', 'Suburban 1500', 1993, 571);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'Truck', 1994, 562);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Venture', 2005, 781);
insert into cars (maker, model, year, person_id) values ('Mazda', 'RX-7', 1993, 513);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'Firebird', 1997, 755);
insert into cars (maker, model, year, person_id) values ('Ford', 'F250', 2010, 606);
insert into cars (maker, model, year, person_id) values ('Lincoln', 'Navigator', 2006, 241);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'GTO', 1994, 432);
insert into cars (maker, model, year, person_id) values ('Ford', 'Ranger', 1993, 239);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'SLK-Class', 2012, 27);
insert into cars (maker, model, year, person_id) values ('Mazda', 'B2600', 1987, 842);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Celica', 2000, 76);
insert into cars (maker, model, year, person_id) values ('Nissan', 'Quest', 2004, 187);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Prius', 2011, 86);
insert into cars (maker, model, year, person_id) values ('GMC', 'Rally Wagon 1500', 1992, 134);
insert into cars (maker, model, year, person_id) values ('Audi', 'A3', 2011, 707);
insert into cars (maker, model, year, person_id) values ('Subaru', 'Tribeca', 2007, 277);
insert into cars (maker, model, year, person_id) values ('Eagle', 'Talon', 1993, 602);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'Bonneville', 1990, 732);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'Mirage', 2001, 943);
insert into cars (maker, model, year, person_id) values ('Audi', 'S8', 2007, 157);
insert into cars (maker, model, year, person_id) values ('Mazda', 'MPV', 1990, 909);
insert into cars (maker, model, year, person_id) values ('Acura', 'RL', 2006, 558);
insert into cars (maker, model, year, person_id) values ('Honda', 'S2000', 2008, 931);
insert into cars (maker, model, year, person_id) values ('Lexus', 'IS F', 2010, 733);
insert into cars (maker, model, year, person_id) values ('Subaru', 'XT', 1988, 310);
insert into cars (maker, model, year, person_id) values ('Mercury', 'Capri', 1994, 183);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Suburban 1500', 2001, 422);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'SSR', 2003, 690);
insert into cars (maker, model, year, person_id) values ('BMW', '5 Series', 2007, 874);
insert into cars (maker, model, year, person_id) values ('Honda', 'Passport', 1994, 503);
insert into cars (maker, model, year, person_id) values ('Oldsmobile', 'Alero', 2000, 723);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Ram Van 1500', 1997, 144);
insert into cars (maker, model, year, person_id) values ('Lexus', 'IS-F', 2011, 313);
insert into cars (maker, model, year, person_id) values ('Maserati', 'GranTurismo', 2009, 204);
insert into cars (maker, model, year, person_id) values ('Ford', 'F350', 2012, 711);
insert into cars (maker, model, year, person_id) values ('Isuzu', 'Axiom', 2004, 626);
insert into cars (maker, model, year, person_id) values ('Panoz', 'Esperante', 2008, 868);
insert into cars (maker, model, year, person_id) values ('Lexus', 'GS', 2011, 921);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Blazer', 2005, 541);
insert into cars (maker, model, year, person_id) values ('Mazda', 'Millenia', 2001, 986);
insert into cars (maker, model, year, person_id) values ('Buick', 'Regal', 2001, 721);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Land Cruiser', 1993, 500);
insert into cars (maker, model, year, person_id) values ('Nissan', 'Xterra', 2001, 900);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Camaro', 1973, 269);
insert into cars (maker, model, year, person_id) values ('Mazda', 'Mazda2', 2012, 822);
insert into cars (maker, model, year, person_id) values ('GMC', 'Rally Wagon G3500', 1996, 895);
insert into cars (maker, model, year, person_id) values ('Hyundai', 'Excel', 1993, 961);
insert into cars (maker, model, year, person_id) values ('Ford', 'Thunderbird', 1977, 191);
insert into cars (maker, model, year, person_id) values ('Buick', 'Reatta', 1991, 435);
insert into cars (maker, model, year, person_id) values ('Isuzu', 'Trooper', 2001, 640);
insert into cars (maker, model, year, person_id) values ('Honda', 'Accord', 2004, 704);
insert into cars (maker, model, year, person_id) values ('GMC', 'Canyon', 2004, 109);
insert into cars (maker, model, year, person_id) values ('BMW', '5 Series', 2001, 519);
insert into cars (maker, model, year, person_id) values ('Volvo', 'XC90', 2010, 246);
insert into cars (maker, model, year, person_id) values ('GMC', '3500 Club Coupe', 1992, 25);
insert into cars (maker, model, year, person_id) values ('Oldsmobile', 'Bravada', 1994, 488);
insert into cars (maker, model, year, person_id) values ('Honda', 'Prelude', 1997, 527);
insert into cars (maker, model, year, person_id) values ('Lexus', 'GS', 1996, 984);
insert into cars (maker, model, year, person_id) values ('Lincoln', 'Continental', 2002, 819);
insert into cars (maker, model, year, person_id) values ('Subaru', 'Impreza', 2002, 522);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Corvette', 1967, 156);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'SLR McLaren', 2009, 933);
insert into cars (maker, model, year, person_id) values ('BMW', '1 Series', 2011, 942);
insert into cars (maker, model, year, person_id) values ('Hyundai', 'Accent', 2011, 590);
insert into cars (maker, model, year, person_id) values ('Eagle', 'Vision', 1996, 340);
insert into cars (maker, model, year, person_id) values ('BMW', 'M3', 2009, 379);
insert into cars (maker, model, year, person_id) values ('Porsche', '968', 1994, 123);
insert into cars (maker, model, year, person_id) values ('Jaguar', 'S-Type', 2006, 239);
insert into cars (maker, model, year, person_id) values ('Suzuki', 'Swift', 1999, 677);
insert into cars (maker, model, year, person_id) values ('Toyota', 'FJ Cruiser', 2007, 837);
insert into cars (maker, model, year, person_id) values ('Maserati', 'Spyder', 2002, 751);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Caliber', 2012, 166);
insert into cars (maker, model, year, person_id) values ('Infiniti', 'G', 2002, 24);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Nitro', 2007, 258);
insert into cars (maker, model, year, person_id) values ('Lexus', 'LS', 2006, 181);
insert into cars (maker, model, year, person_id) values ('BMW', 'X3', 2004, 218);
insert into cars (maker, model, year, person_id) values ('Ford', 'Explorer', 1997, 830);
insert into cars (maker, model, year, person_id) values ('BMW', 'X6', 2013, 251);
insert into cars (maker, model, year, person_id) values ('Porsche', '928', 1990, 642);
insert into cars (maker, model, year, person_id) values ('Panoz', 'Esperante', 2006, 843);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'CL-Class', 2000, 47);
insert into cars (maker, model, year, person_id) values ('Porsche', 'Panamera', 2012, 77);
insert into cars (maker, model, year, person_id) values ('Chevrolet', '1500', 1999, 901);
insert into cars (maker, model, year, person_id) values ('Chrysler', 'Sebring', 1999, 113);
insert into cars (maker, model, year, person_id) values ('Ford', 'Explorer', 2003, 331);
insert into cars (maker, model, year, person_id) values ('GMC', 'Rally Wagon 3500', 1993, 235);
insert into cars (maker, model, year, person_id) values ('Saab', '9-5', 1999, 358);
insert into cars (maker, model, year, person_id) values ('Ford', 'F250', 2011, 809);
insert into cars (maker, model, year, person_id) values ('Land Rover', 'Defender 90', 1994, 318);
insert into cars (maker, model, year, person_id) values ('Toyota', 'FJ Cruiser', 2011, 567);
insert into cars (maker, model, year, person_id) values ('Chrysler', 'LeBaron', 1995, 878);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'Cordia', 1986, 592);
insert into cars (maker, model, year, person_id) values ('Mazda', 'RX-8', 2008, 900);
insert into cars (maker, model, year, person_id) values ('Lexus', 'SC', 2007, 962);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Echo', 2005, 655);
insert into cars (maker, model, year, person_id) values ('Ford', 'Ranger', 1985, 781);
insert into cars (maker, model, year, person_id) values ('Chrysler', 'New Yorker', 1996, 741);
insert into cars (maker, model, year, person_id) values ('Mazda', 'MX-6', 1996, 681);
insert into cars (maker, model, year, person_id) values ('Ford', 'Econoline E150', 1995, 346);
insert into cars (maker, model, year, person_id) values ('Subaru', 'Baja', 2005, 423);
insert into cars (maker, model, year, person_id) values ('Oldsmobile', '88', 1993, 276);
insert into cars (maker, model, year, person_id) values ('Volkswagen', 'Eurovan', 1992, 2);
insert into cars (maker, model, year, person_id) values ('Kia', 'Sportage', 2007, 698);
insert into cars (maker, model, year, person_id) values ('Hummer', 'H2', 2004, 7);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Camry', 2000, 741);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'GTO', 1991, 822);
insert into cars (maker, model, year, person_id) values ('Lamborghini', 'Countach', 1989, 871);
insert into cars (maker, model, year, person_id) values ('Land Rover', 'Range Rover Sport', 2011, 593);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'CLS-Class', 2012, 119);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'G-Series G30', 1994, 23);
insert into cars (maker, model, year, person_id) values ('Infiniti', 'G', 2002, 189);
insert into cars (maker, model, year, person_id) values ('Hyundai', 'Excel', 1993, 681);
insert into cars (maker, model, year, person_id) values ('Toyota', 'RAV4', 2008, 366);
insert into cars (maker, model, year, person_id) values ('Land Rover', 'LR3', 2005, 425);
insert into cars (maker, model, year, person_id) values ('Honda', 'Accord', 2012, 670);
insert into cars (maker, model, year, person_id) values ('Ford', 'Escort', 1999, 230);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'Sprinter', 2010, 651);
insert into cars (maker, model, year, person_id) values ('Volkswagen', 'GTI', 1996, 359);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'Bonneville', 1994, 566);
insert into cars (maker, model, year, person_id) values ('Volvo', 'S40', 2001, 160);
insert into cars (maker, model, year, person_id) values ('Kia', 'Soul', 2010, 647);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'E-Class', 2004, 834);
insert into cars (maker, model, year, person_id) values ('Ford', 'Escape', 2003, 234);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Impala', 2004, 965);
insert into cars (maker, model, year, person_id) values ('Cadillac', 'Escalade EXT', 2005, 747);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Avalanche 1500', 2003, 154);
insert into cars (maker, model, year, person_id) values ('Buick', 'LaCrosse', 2006, 702);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'GTO', 1996, 267);
insert into cars (maker, model, year, person_id) values ('GMC', 'Savana 2500', 2009, 744);
insert into cars (maker, model, year, person_id) values ('Suzuki', 'Swift', 2004, 884);
insert into cars (maker, model, year, person_id) values ('Lexus', 'RX', 2012, 593);
insert into cars (maker, model, year, person_id) values ('Hyundai', 'Sonata', 1996, 320);
insert into cars (maker, model, year, person_id) values ('BMW', '645', 2005, 557);
insert into cars (maker, model, year, person_id) values ('GMC', 'Savana 3500', 2005, 445);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Tercel', 1993, 25);
insert into cars (maker, model, year, person_id) values ('Suzuki', 'Esteem', 1997, 47);
insert into cars (maker, model, year, person_id) values ('Infiniti', 'QX', 2006, 171);
insert into cars (maker, model, year, person_id) values ('Audi', 'RS 6', 2003, 817);
insert into cars (maker, model, year, person_id) values ('Honda', 'Fit', 2011, 869);
insert into cars (maker, model, year, person_id) values ('Aston Martin', 'Rapide', 2010, 982);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Xtra', 1993, 890);
insert into cars (maker, model, year, person_id) values ('Maserati', 'Spyder', 2004, 919);
insert into cars (maker, model, year, person_id) values ('Acura', 'Integra', 1995, 806);
insert into cars (maker, model, year, person_id) values ('Cadillac', 'Fleetwood', 1992, 291);
insert into cars (maker, model, year, person_id) values ('Porsche', 'Boxster', 1998, 870);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Corvette', 1966, 729);
insert into cars (maker, model, year, person_id) values ('Cadillac', 'DTS', 2011, 408);
insert into cars (maker, model, year, person_id) values ('Mazda', '626', 1997, 984);
insert into cars (maker, model, year, person_id) values ('Buick', 'LeSabre', 1994, 941);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Camry', 2000, 825);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Stealth', 1993, 540);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'Torrent', 2007, 330);
insert into cars (maker, model, year, person_id) values ('Hummer', 'H1', 1993, 375);
insert into cars (maker, model, year, person_id) values ('Land Rover', 'Range Rover', 2007, 461);
insert into cars (maker, model, year, person_id) values ('Mercury', 'Grand Marquis', 1987, 759);
insert into cars (maker, model, year, person_id) values ('Buick', 'Estate', 1990, 255);
insert into cars (maker, model, year, person_id) values ('Cadillac', 'Seville', 1992, 961);
insert into cars (maker, model, year, person_id) values ('Mercury', 'Grand Marquis', 1990, 974);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Cruze', 2011, 229);
insert into cars (maker, model, year, person_id) values ('GMC', 'Sierra 3500', 2000, 441);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Paseo', 1992, 628);
insert into cars (maker, model, year, person_id) values ('Cadillac', 'SRX', 2004, 882);
insert into cars (maker, model, year, person_id) values ('Honda', 'Prelude', 1997, 340);
insert into cars (maker, model, year, person_id) values ('Buick', 'Coachbuilder', 1990, 525);
insert into cars (maker, model, year, person_id) values ('Ford', 'E-Series', 2007, 309);
insert into cars (maker, model, year, person_id) values ('BMW', 'M3', 2004, 120);
insert into cars (maker, model, year, person_id) values ('Land Rover', 'Defender 90', 1995, 331);
insert into cars (maker, model, year, person_id) values ('Toyota', 'MR2', 2000, 126);
insert into cars (maker, model, year, person_id) values ('Nissan', '200SX', 1996, 300);
insert into cars (maker, model, year, person_id) values ('BMW', 'X6', 2012, 914);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Camry Hybrid', 2010, 737);
insert into cars (maker, model, year, person_id) values ('Audi', '5000S', 1987, 56);
insert into cars (maker, model, year, person_id) values ('Honda', 'Accord', 1999, 694);
insert into cars (maker, model, year, person_id) values ('Lexus', 'IS', 2012, 255);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Dakota', 2001, 822);
insert into cars (maker, model, year, person_id) values ('Jaguar', 'X-Type', 2003, 189);
insert into cars (maker, model, year, person_id) values ('Ford', 'E150', 2012, 749);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'Galant', 2004, 423);
insert into cars (maker, model, year, person_id) values ('Land Rover', 'Range Rover', 2010, 868);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'Tempest', 1966, 939);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Blazer', 1995, 289);
insert into cars (maker, model, year, person_id) values ('Mazda', '626', 1992, 636);
insert into cars (maker, model, year, person_id) values ('Buick', 'Skylark', 1997, 696);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'Grand Prix', 1975, 545);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Tahoe', 2009, 95);
insert into cars (maker, model, year, person_id) values ('GMC', 'Savana 2500', 2001, 24);
insert into cars (maker, model, year, person_id) values ('Saab', '900', 1988, 437);
insert into cars (maker, model, year, person_id) values ('Kia', 'Soul', 2010, 197);
insert into cars (maker, model, year, person_id) values ('Chrysler', 'New Yorker', 1992, 99);
insert into cars (maker, model, year, person_id) values ('Lexus', 'RX', 2010, 131);
insert into cars (maker, model, year, person_id) values ('Mercury', 'Cougar', 1991, 31);
insert into cars (maker, model, year, person_id) values ('BMW', '8 Series', 1994, 111);
insert into cars (maker, model, year, person_id) values ('Lexus', 'GX', 2006, 482);
insert into cars (maker, model, year, person_id) values ('Citroën', 'CX', 1989, 847);
insert into cars (maker, model, year, person_id) values ('Audi', 'S5', 2012, 637);
insert into cars (maker, model, year, person_id) values ('Maserati', 'Karif', 1989, 250);
insert into cars (maker, model, year, person_id) values ('Lexus', 'IS-F', 2009, 736);
insert into cars (maker, model, year, person_id) values ('Land Rover', 'Range Rover', 1996, 471);
insert into cars (maker, model, year, person_id) values ('Lincoln', 'Continental Mark VII', 1991, 714);
insert into cars (maker, model, year, person_id) values ('Porsche', 'Boxster', 2006, 486);
insert into cars (maker, model, year, person_id) values ('Pontiac', 'Bonneville', 1999, 936);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', '600SL', 1993, 558);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Beretta', 1992, 533);
insert into cars (maker, model, year, person_id) values ('Mazda', 'B-Series', 1991, 76);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'C-Class', 2001, 456);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'Sprinter 2500', 2011, 822);
insert into cars (maker, model, year, person_id) values ('BMW', 'X5', 2004, 708);
insert into cars (maker, model, year, person_id) values ('Lincoln', 'Blackwood', 2003, 628);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Cobalt SS', 2008, 630);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Camaro', 2010, 561);
insert into cars (maker, model, year, person_id) values ('Suzuki', 'Grand Vitara', 2005, 34);
insert into cars (maker, model, year, person_id) values ('Mercedes-Benz', 'C-Class', 2009, 400);
insert into cars (maker, model, year, person_id) values ('GMC', 'Envoy', 2005, 879);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Ram 3500', 2005, 499);
insert into cars (maker, model, year, person_id) values ('Volvo', 'S40', 2007, 258);
insert into cars (maker, model, year, person_id) values ('Jeep', 'Wrangler', 2008, 987);
insert into cars (maker, model, year, person_id) values ('Hyundai', 'Santa Fe', 2007, 3);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Tacoma', 2008, 712);
insert into cars (maker, model, year, person_id) values ('Volvo', 'S80', 2003, 781);
insert into cars (maker, model, year, person_id) values ('Kia', 'Spectra', 2005, 994);
insert into cars (maker, model, year, person_id) values ('Cadillac', 'DeVille', 1995, 630);
insert into cars (maker, model, year, person_id) values ('BMW', '5 Series', 2009, 812);
insert into cars (maker, model, year, person_id) values ('Ferrari', '612 Scaglietti', 2006, 381);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Caliber', 2008, 420);
insert into cars (maker, model, year, person_id) values ('Ford', 'Bronco', 1986, 481);
insert into cars (maker, model, year, person_id) values ('Ford', 'Mustang', 1985, 799);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Astro', 1995, 125);
insert into cars (maker, model, year, person_id) values ('Jaguar', 'XJ Series', 1995, 556);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Stratus', 1998, 479);
insert into cars (maker, model, year, person_id) values ('Land Rover', 'Range Rover Sport', 2010, 213);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Suburban 2500', 2001, 137);
insert into cars (maker, model, year, person_id) values ('Ford', 'Explorer', 1995, 759);
insert into cars (maker, model, year, person_id) values ('Ford', 'F150', 2011, 294);
insert into cars (maker, model, year, person_id) values ('Ford', 'Mustang', 1997, 800);
insert into cars (maker, model, year, person_id) values ('Hyundai', 'Tiburon', 2009, 529);
insert into cars (maker, model, year, person_id) values ('Daewoo', 'Nubira', 2002, 626);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Express 3500', 1997, 902);
insert into cars (maker, model, year, person_id) values ('Ford', 'Laser', 1989, 214);
insert into cars (maker, model, year, person_id) values ('Dodge', 'Ram Van B150', 1993, 648);
insert into cars (maker, model, year, person_id) values ('Ford', 'Bronco II', 1985, 978);
insert into cars (maker, model, year, person_id) values ('Toyota', 'Matrix', 2009, 496);
insert into cars (maker, model, year, person_id) values ('Ford', 'Thunderbird', 2002, 7);
insert into cars (maker, model, year, person_id) values ('Mitsubishi', 'Mighty Max Macro', 1994, 455);
insert into cars (maker, model, year, person_id) values ('Cadillac', 'Catera', 1997, 219);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Aveo', 2008, 714);
insert into cars (maker, model, year, person_id) values ('Chevrolet', 'Avalanche 1500', 2003, 909);
